version: 0.2

env:
  variables:
    PROJECT: HelloWorld
    DOTNET_FRAMEWORK: 4.8
phases:
  build:
    commands:
      - nuget restore
      - msbuild $env:PROJECT.sln /p:TargetFrameworkVersion=v$env:DOTNET_FRAMEWORK /p:Configuration=Release /p:DeployOnBuild=True /p:DeployDefaultTarget=WebPublish /p:Platform="Any CPU" /p:WebPublishMethod=FileSystem /p:DeleteExistingFiles=True /p:publishUrl=bin\app.publish\
artifacts:
  files:
    - 'HelloWorld/bin/*'
