version: 0.2

env:
  variables:
    PROJECT: HelloWorld
    DOTNET_FRAMEWORK: 4.8
phases:
  build:
    commands:
      - nuget restore
      - msbuild HelloWorld.sln /p:TargetFrameworkVersion=v$env:DOTNET_FRAMEWORK /p:Configuration=Release /p:DeployOnBuild=True /p:Platform="Any CPU" /p:DeleteExistingFiles=True /p:DeployDefaultTarget=WebPublish /p:WebPublishMethod=FileSystem /p:publishUrl=C:\artifacts
artifacts:
  files:
    - '**/*'
  base-directory: "C:\\artifacts"
  name: HelloWorld-$(Get-Date -UFormat "%Y%m%d-%H%M%S")
